const ALERT="ALERT"
const REFETCH_CHATS="REFETCH_CHATS"
const NEW_ATTACHMENTS="NEW_ATTACHMENTS"
const NEW_MESSAGE_ALERT="NEW_MESSAGE_ALERT"
const NEW_REQUEST="NEW_REQUEST"
const NEW_MESSAGE="NEW_MESSAGE" 
const START_TYPING="START_TYPING"
const STOP_TYPING="STOP_TYPING"
const NEW_REQUEST_ACCEPTED="NEW_REQUEST_ACCEPTED"
const GROUP_LEFT="GROUP_LEFT"

export {ALERT,REFETCH_CHATS,NEW_ATTACHMENTS,NEW_MESSAGE,NEW_MESSAGE_ALERT,NEW_REQUEST,START_TYPING,STOP_TYPING,NEW_REQUEST_ACCEPTED,GROUP_LEFT}